-- ==============================================================================
-- SLSCM Lab — Authoritative PostgreSQL Database Schema for Supabase
-- Single Source of Truth (SSOT) with Row Level Security (RLS)
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ------------------------------------------------------------------------------
-- 1. INSTITUTIONS & COLLABORATING UNIVERSITIES
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.institutions (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    short_name TEXT,
    country TEXT,
    city TEXT,
    website TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ------------------------------------------------------------------------------
-- 2. RESEARCH PILLARS (Strategic Foundations)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.research_pillars (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    topics JSONB DEFAULT '[]'::jsonb,
    featured_venues JSONB DEFAULT '[]'::jsonb,
    display_order INTEGER DEFAULT 0,
    status TEXT DEFAULT 'active'
);

-- ------------------------------------------------------------------------------
-- 3. PEOPLE (Faculty, Researchers, Alumni, Tech Leads)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.people (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    name_en TEXT,
    title TEXT,
    role_badge TEXT,
    category TEXT NOT NULL, -- 'faculty', 'web_tech_lead', 'student_researcher', 'alumni'
    affiliation TEXT,
    affiliation_id TEXT REFERENCES public.institutions(id) ON DELETE SET NULL,
    email TEXT,
    office TEXT,
    bio TEXT,
    avatar TEXT,
    major TEXT,
    current_status TEXT,
    status TEXT DEFAULT 'active',
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.person_research_interests (
    person_id TEXT NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
    interest TEXT NOT NULL,
    order_index INTEGER DEFAULT 0,
    PRIMARY KEY (person_id, interest)
);

CREATE TABLE IF NOT EXISTS public.person_featured_publications (
    person_id TEXT NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
    publication_title TEXT NOT NULL,
    order_index INTEGER DEFAULT 0,
    PRIMARY KEY (person_id, publication_title)
);

-- ------------------------------------------------------------------------------
-- 4. PUBLICATIONS (Journals, Conferences, Book Chapters)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.publications (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    year INTEGER NOT NULL,
    venue TEXT NOT NULL,
    type TEXT NOT NULL,
    doi TEXT,
    link TEXT,
    abstract TEXT,
    abstract_source TEXT,
    bibtex TEXT,
    research_pillar TEXT,
    primary_pillar_id TEXT REFERENCES public.research_pillars(id) ON DELETE SET NULL,
    keywords JSONB DEFAULT '[]'::jsonb,
    is_featured BOOLEAN DEFAULT false,
    badge TEXT,
    status TEXT DEFAULT 'published',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.publication_authors (
    publication_id TEXT NOT NULL REFERENCES public.publications(id) ON DELETE CASCADE,
    person_id TEXT REFERENCES public.people(id) ON DELETE SET NULL,
    author_name TEXT NOT NULL,
    author_order INTEGER NOT NULL,
    is_highlighted BOOLEAN DEFAULT false,
    PRIMARY KEY (publication_id, author_order)
);

-- ------------------------------------------------------------------------------
-- 5. RESEARCH PROJECTS & GRANTS
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.projects (
    id TEXT PRIMARY KEY,
    title_en TEXT NOT NULL,
    title_vi TEXT,
    category TEXT NOT NULL,
    category_en TEXT,
    sponsor TEXT,
    grant_code TEXT,
    period TEXT,
    status TEXT DEFAULT 'Active',
    research_domain TEXT,
    collaboration TEXT,
    description_en TEXT NOT NULL,
    description_vi TEXT,
    methodology TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.project_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    person_id TEXT REFERENCES public.people(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    email TEXT,
    role TEXT,
    affiliation TEXT,
    order_index INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.project_publications (
    project_id TEXT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    publication_id TEXT NOT NULL REFERENCES public.publications(id) ON DELETE CASCADE,
    display_order INTEGER DEFAULT 0,
    PRIMARY KEY (project_id, publication_id)
);

CREATE TABLE IF NOT EXISTS public.project_outcomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    outcome_en TEXT NOT NULL,
    outcome_vi TEXT,
    order_index INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.project_tags (
    project_id TEXT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    tag TEXT NOT NULL,
    PRIMARY KEY (project_id, tag)
);

CREATE TABLE IF NOT EXISTS public.project_pillars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    pillar TEXT NOT NULL,
    description_en TEXT,
    description_vi TEXT
);

CREATE TABLE IF NOT EXISTS public.project_curriculum (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    module_en TEXT,
    module_vi TEXT NOT NULL,
    content_vi TEXT NOT NULL,
    order_index INTEGER DEFAULT 0
);

-- ------------------------------------------------------------------------------
-- 6. SEMINARS & ACADEMIC COLLOQUIA
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.seminars (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    title_vi TEXT,
    speaker TEXT NOT NULL,
    speaker_person_id TEXT REFERENCES public.people(id) ON DELETE SET NULL,
    speaker_role TEXT,
    affiliation TEXT NOT NULL,
    affiliation_id TEXT REFERENCES public.institutions(id) ON DELETE SET NULL,
    date TEXT NOT NULL,
    time TEXT,
    venue TEXT NOT NULL,
    venue_type TEXT NOT NULL, -- 'In-Person', 'Online', 'Hybrid'
    status TEXT DEFAULT 'Archived', -- 'Upcoming', 'Archived'
    category TEXT,
    track TEXT,
    abstract TEXT NOT NULL,
    abstract_en TEXT,
    related_paper_id TEXT REFERENCES public.publications(id) ON DELETE SET NULL,
    related_project_id TEXT REFERENCES public.projects(id) ON DELETE SET NULL,
    slides_available BOOLEAN DEFAULT false,
    recording_available BOOLEAN DEFAULT false,
    slides_url TEXT,
    recording_url TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.seminar_topics (
    seminar_id TEXT NOT NULL REFERENCES public.seminars(id) ON DELETE CASCADE,
    topic TEXT NOT NULL,
    PRIMARY KEY (seminar_id, topic)
);

-- ------------------------------------------------------------------------------
-- 7. EVENTS & NEWS BRIEFS
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.events (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    title_vi TEXT,
    event_date TEXT NOT NULL,
    category TEXT NOT NULL,
    category_vi TEXT,
    badge TEXT,
    summary TEXT NOT NULL,
    summary_en TEXT,
    summary_vi TEXT,
    content_en TEXT,
    content_vi TEXT,
    link TEXT,
    link_label TEXT,
    featured BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.event_tags (
    event_id TEXT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    tag TEXT NOT NULL,
    PRIMARY KEY (event_id, tag)
);

-- ------------------------------------------------------------------------------
-- 8. ACHIEVEMENTS & HALL OF FAME
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.achievements (
    id TEXT PRIMARY KEY,
    person_id TEXT REFERENCES public.people(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    name_en TEXT,
    avatar TEXT,
    achievement TEXT NOT NULL,
    achievement_en TEXT,
    destination_institution TEXT NOT NULL,
    institution_id TEXT REFERENCES public.institutions(id) ON DELETE SET NULL,
    country TEXT NOT NULL,
    year INTEGER NOT NULL,
    award_type TEXT,
    field TEXT,
    former_background_en TEXT,
    advisors TEXT,
    featured BOOLEAN DEFAULT false,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ------------------------------------------------------------------------------
-- 9. GLOBAL ACADEMIC PARTNERS
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.global_academic_partners (
    id TEXT PRIMARY KEY,
    institution TEXT NOT NULL,
    institution_id TEXT REFERENCES public.institutions(id) ON DELETE SET NULL,
    country TEXT NOT NULL,
    key_collaborators TEXT DEFAULT '',
    research_focus TEXT DEFAULT '',
    order_index INTEGER DEFAULT 0
);

-- ------------------------------------------------------------------------------
-- 10. SOCIAL POSTS (Facebook Fanpage Feed)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.social_posts (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    abstract TEXT,
    journal TEXT,
    paper_title TEXT,
    authors JSONB DEFAULT '[]'::jsonb,
    organizer TEXT,
    collaboration TEXT,
    link TEXT,
    action_label TEXT,
    venue TEXT,
    display_order INTEGER DEFAULT 0
);

-- ------------------------------------------------------------------------------
-- 11. LAB OVERVIEW & METADATA
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lab_overview (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================

-- Enable RLS across all tables
ALTER TABLE public.institutions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.research_pillars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.people ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.person_research_interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.person_featured_publications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.publications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.publication_authors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_publications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_outcomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_pillars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_curriculum ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seminars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seminar_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.global_academic_partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_overview ENABLE ROW LEVEL SECURITY;

-- 1. Public Read Access (Anyone can read data on the website)
CREATE POLICY "Allow public read access" ON public.institutions FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.research_pillars FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.people FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.person_research_interests FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.person_featured_publications FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.publications FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.publication_authors FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.project_leads FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.project_publications FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.project_outcomes FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.project_tags FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.project_pillars FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.project_curriculum FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.seminars FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.seminar_topics FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.events FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.event_tags FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.achievements FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.global_academic_partners FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.social_posts FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.lab_overview FOR SELECT USING (true);

-- 2. Authenticated Full Access (Lab Admins & Members can insert/update/delete)
CREATE POLICY "Allow authenticated full access" ON public.institutions FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.research_pillars FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.people FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.person_research_interests FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.person_featured_publications FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.publications FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.publication_authors FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.projects FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.project_leads FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.project_publications FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.project_outcomes FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.project_tags FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.project_pillars FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.project_curriculum FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.seminars FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.seminar_topics FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.events FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.event_tags FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.achievements FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.global_academic_partners FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.social_posts FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access" ON public.lab_overview FOR ALL TO authenticated USING (true) WITH CHECK (true);
